matches:
  - trigger: ":zero:"
    replace: "\uE000"
    label: |
      <p style="font-family: Bard">&#xE000</p>
  - trigger: ":one:"
    replace: "\uE001"
  - trigger: ":two:"
    replace: "\uE002"
  - trigger: ":three:"
    replace: "\uE003"
  - trigger: ":four:"
    replace: "\uE004"
  - trigger: ":five:"
    replace: "\uE005"
  - trigger: ":six:"
    replace: "\uE006"
  - trigger: ":seven:"
    replace: "\uE007"
  - trigger: ":eight:"
    replace: "\uE008"
  - trigger: ":nine:"
    replace: "\uE009"
  - trigger: ":ten:"
    replace: "\uE00A"
  - trigger: ":eleven:"
    replace: "\uE00B"
  - trigger: ":abbey:"
    replace: "\uE00C"
  - trigger: ":question:"
    replace: "\uE00D"
  - trigger: ":me:"
    replace: "\uE00E"
  - trigger: ":you:"
    replace: "\uE00F"
  - trigger: ":be:"
    replace: "\uE010"
  - trigger: ":plural:"
    replace: "\uE011"
  - trigger: ":bard:"
    replace: "\uE012"
  - trigger: ":possess:"
    replace: "\uE013"
  - trigger: ":like:"
    replace: "\uE014"
  - trigger: ":theatre:"
    replace: "\uE015"
  - trigger: ":go:"
    replace: "\uE016"
  - trigger: ":agora:"
    replace: "\uE017"
  - trigger: ":ascend:"
    replace: "\uE018"
  - trigger: ":beauty:"
    replace: "\uE019"
  - trigger: ":book:"
    replace: "\uE01A"
  - trigger: ":brother:"
    replace: "\uE01B"
  - trigger: ":comedy:"
    replace: "\uE01C"
  - trigger: ":compass:"
    replace: "\uE01D"
  - trigger: ":east:"
    replace: "\uE01E"
  - trigger: ":find:"
    replace: "\uE01F"
  - trigger: ":fire:"
    replace: "\uE020"
  - trigger: ":fortress:"
    replace: "\uE021"
  - trigger: ":free:"
    replace: "\uE022"
  - trigger: ":greetings:"
    replace: "\uE023"
  - trigger: ":hammer:"
    replace: "\uE024"
  - trigger: ":idiot:"
    replace: "\uE025"
  - trigger: ":instrument:"
    replace: "\uE026"
  - trigger: ":man:"
    replace: "\uE027"
  - trigger: ":monster:"
    replace: "\uE028"
  - trigger: ":music:"
    replace: "\uE029"
  - trigger: ":north:"
    replace: "\uE02A"
  - trigger: ":not:"
    replace: "\uE02B"
  - trigger: ":path:"
    replace: "\uE02C"
  - trigger: ":play:"
    replace: "\uE02D"
  - trigger: ":pliers:"
    replace: "\uE02E"
  - trigger: ":saw:"
    replace: "\uE02F"
  - trigger: ":seek:"
    replace: "\uE030"
  - trigger: ":south:"
    replace: "\uE031"
  - trigger: ":warrior:"
    replace: "\uE032"
  - trigger: ":weapon:"
    replace: "\uE033"
  - trigger: ":west:"
    replace: "\uE034"
  - trigger: ":windmill:"
    replace: "\uE035"